DROP TABLE IF EXISTS EmergencyContact;
DROP TABLE IF EXISTS Tickets;
DROP TABLE IF EXISTS Bookings;
DROP TABLE IF EXISTS Reservations;
DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS Venues;
DROP TABLE IF EXISTS Organizers;
DROP TABLE IF EXISTS VIP;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Users;


